name: Test on Multiple OS versions
on:
  push:
    branches:
      - master
jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

  steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: run tests
      run: |
        echo "Running tests on ${{ matrix.os }}"
        bash test.sh
