name: Test on multiple Nodejs versions
on:
    push:
        branches:
            - master
jobs:
    test-matrix:
        runs-on: ${{ matrix.nodejs_version }}
        strategy:
            matrix:
                nodejs_version: [Node.js 14.21.1, Node.js 16.18.1, Node.js 18.20.0]
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: run tests
              run: echo "Running tests on ${{ matrix.nodejs_version }}"